### ISSUE TITLE
Update "Database Manipulation" Wiki Page

### ISSUE THREAD

**Issue by TimCreasman** [PointSource/checkit-blueoak#20]
Update the asset schema code snippet. Add in sections that describe the process for editing and removing assets.

**Comment by tinoweiss** [comment]
@TimCreasman Please add in sections describing the process for editing and removing assets.

**Comment by tinoweiss** [comment]
Asset schema code snippet and general formatting has been updated.

**Comment by tinoweiss** [comment]
Update Database Manipulation page to display an overview of how to modify assets via the CheckIT application and via a third party application. Also document how to add an admin user. See #39 for moving QR Code documentation to another page.
