### ISSUE TITLE
Remove the Calendar Event Functionality

### ISSUE THREAD

**Issue by TimCreasman** [PointSource/checkit-blueoak#38]
The calendar event functionality, which would notify users when a device is overdue, is no longer required. Remove the associated Cordova plugin, packages, and code.

**Comment by TimCreasman** [comment]
Calendar functionality deleted with commit: f9a6dfcc22d78420a88444168626278dcdc6145f.

The calendar configurations still exist within the client config. The PR #53 removes this.

**Comment by tinoweiss** [comment]
Cordova calendar plugin removed with 0a46bbe0e5ce3ab41eda99246aab087c0ca0def5.
